////PACKAGE COM.MY.CONTROL;
////
////IMPORT ORG.SPRINGFRAMEWORK.BEANS.FACTORY.ANNOTATION.AUTOWIRED;
////IMPORT ORG.SPRINGFRAMEWORK.HTTP.HTTPSTATUS;
////IMPORT ORG.SPRINGFRAMEWORK.HTTP.RESPONSEENTITY;
////IMPORT ORG.SPRINGFRAMEWORK.STEREOTYPE.CONTROLLER;
////IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.PATHVARIABLE;
////IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.REQUESTMAPPING;
////IMPORT ORG.SPRINGFRAMEWORK.WEB.BIND.ANNOTATION.RESPONSEBODY;
////
////IMPORT COM.MY.EXCEPTION.FINDEXCEPTION;
////IMPORT COM.MY.MODEL.PAGEBEAN;
////IMPORT COM.MY.SERVICE.BOARDSERVICE;
////IMPORT COM.MY.VO.BOARD;
////
////@CONTROLLER
////@REQUESTMAPPING("/BOARD/*")
////PUBLIC CLASS BOARDRESTCONTROLLER {
////	@AUTOWIRED
////	PRIVATE BOARDSERVICE SERVICE;
////	
////	@REQUESTMAPPING("/BOARDREST")
////	PUBLIC VOID ROOT() {
////		// / WEB-INF/JSP/OBARDREST.JSP로 포워드
////		
////	}
//	@REQUESTMAPPING("/BOARDREST")
//	PUBLIC STRING ROOT2() {
//		RETURN "/BOARDREST"; //  WEB-INF/JSP/OBARDREST.JSP로 포워드
//	}
//	
//	@REQUESTMAPPING("/DEATIL/{BOARD_NO}")
//	@RESPONSEBODY
//	PUBLIC RESPONSEENTITY<BOARD> DETAIL(@PATHVARIABLE INT BOARD_NO){
//			 BOARD BOARD =NULL;
//		TRY {
//			 BOARD = SERVICE.FINDBYNO(BOARD_NO);
//			RETURN (RESPONSEENTITY<BOARD>)RESPONSEENTITY.STATUS(HTTPSTATUS.OK).BODY(BOARD);
//		}CATCH(FINDEXCEPTION E) {
//			E.PRINTSTACKTRACE();
//			RETURN (RESPONSEENTITY<BOARD>)RESPONSEENTITY.STATUS(HTTPSTATUS.INTERNAL_SERVER_ERROR).BODY(BOARD);
//		}
//		
//	}
//	@REQUESTMAPPING("/LIST/{CURRENTPAGE}")
//	@RESPONSEBODY
//	PUBLIC RESPONSEENTITY<PAGEBEAN> LIST(@PATHVARIABLE(VALUE="CURRENTPAGE",REQUIRED=FALSE) INTEGER CP){
//		INT CURRENTPAGE = 1;
//		
//		IF(CP !=NULL) {
//			CURRENTPAGE = CP;
//		}
//		PAGEBEAN PB =NULL;
//		TRY {
//		PB = SERVICE.FINDALL(CURRENTPAGE);
//		RETURN (RESPONSEENTITY<PAGEBEAN>)RESPONSEENTITY.STATUS(HTTPSTATUS.OK).BODY(PB);
//	   }CATCH (FINDEXCEPTION E) {
//					E.PRINTSTACKTRACE();
//					RETURN (RESPONSEENTITY<PAGEBEAN>)RESPONSEENTITY.STATUS(HTTPSTATUS.INTERNAL_SERVER_ERROR).BODY(PB);
//				}
//		
//	}
//
////   	
////   PROTECTED VOID SERVICE(HTTPSERVLETREQUEST REQUEST, HTTPSERVLETRESPONSE RESPONSE) THROWS SERVLETEXCEPTION, IOEXCEPTION {
//
////	   STRING PATHINFO = REQUEST.GETPATHINFO();
////	   STRING SERVLETPATH = "";
////	   IF ("/WRITE".EQUALS(PATHINFO)) {//글쓰기
////		   STRING BOARD_TITLE =REQUEST.GETPARAMETER("BOARD_TITLE");
////	      STRING BOARD_WRITER = REQUEST.GETPARAMETER("BOARD_WRITER");
////	      STRING BOARD_CONTENT = REQUEST.GETPARAMETER("BOARD_CONTENT");
////	      SYSTEM.OUT.PRINTLN(BOARD_CONTENT);
////	      BOARD BOARD = NEW BOARD(BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT);
////	      TRY {
////	         SERVICE.WRITE(BOARD);
////	         SERVLETPATH = "/SUCCESS.JSP";
////	         REQUESTDISPATCHER RD = REQUEST.GETREQUESTDISPATCHER(SERVLETPATH);
////			 RD.FORWARD(REQUEST, RESPONSE);
////	      } CATCH (ADDEXCEPTION E) {
////	         E.PRINTSTACKTRACE();
////	      }
////	   }ELSE IF("/REPLAY".EQUALS(PATHINFO)) {//답글쓰기
////		   
////	   }ELSE IF("/DETAIL".EQUALS(PATHINFO)) {//디테일보기
////		  
////		   
////	   }
////	   
////	   ELSE IF("/LIST".EQUALS(PATHINFO)) {//게시물 목록보기
////		   LIST<BOARD> LIST ;
////		   TRY {
////			   STRING STRPAGE = REQUEST.GETPARAMETER("CURRENTPAGE");
////			   INT CURRENTPAGE = 1;
////			   //IF(STRPAGE != NULL && !STRPAGE.EQUALS("")){
////			   IF(!"".EQUALS(STRPAGE)) { //IF(!STRPAGE.EQUALS(""){
////			   CURRENTPAGE = INTEGER.PARSEINT(STRPAGE);
////			   }
////			   COM.MY.MODEL.PAGEBEAN PB = SERVICE.FINDALL(CURRENTPAGE);
////			   STRING URL = REQUEST.GETSERVLETPATH() + REQUEST.GETPATHINFO();
////			   PB.SETURL(URL);
////			   SYSTEM.OUT.PRINTLN(PB);
//////			   LIST = SERVICE.FINDALL(CURRENTPAGE);
////			   //REQUEST.SETATTRIBUTE("LIST", LIST);
////			   REQUEST.SETATTRIBUTE("PB", PB);
////			   SERVLETPATH = "/BOARDLIST.JSP";
////			   REQUESTDISPATCHER RD = REQUEST.GETREQUESTDISPATCHER(SERVLETPATH);
////			   RD.FORWARD(REQUEST, RESPONSE);
//////			   FOR(BOARD B:LIST) {
//////				   SYSTEM.OUT.PRINTLN(B); //B TOSTRING 자동호출
//////			   }
////		   }CATCH (FINDEXCEPTION E) {
////				   E.PRINTSTACKTRACE();
////			   }
////		   }   
////	   }
//
////글쓰기
////	
//	// 답변보기
////	  INT PARENT_NO = 10;
////	  STRING BOARD_TITLE = "테스트1";
////      STRING BOARD_WRITER = "작성자1";
////      STRING BOARD_CONTENT = "내용1";
////      BOARD BOARD = NEW BOARD(PARENT_NO,BOARD_TITLE, BOARD_WRITER, BOARD_CONTENT);
////      TRY {
////         SERVICE.REPLY(BOARD);
////      } CATCH (ADDEXCEPTION E) {
////         E.PRINTSTACKTRACE();
////      }
//	//
//
//}
